### ISSUE TITLE
Plugin not loading, probably after update  to 4.3

### ISSUE THREAD

**Issue by carlomontec** [absop/RainbowBrackets#33]
Hello, 
seems that after updating to version 4.3 the plugin is not loading in ST4180 in macOS. Not even the commands in the menu list are available. I tried reinstalling it, but didn't lead to any change.

Thank you!

**Comment by absop** [comment]
Could you put the error message printed in ST's console (by press the shortcut<kbd>ctrl+`<kbf/>) here?

**Comment by yeoooo** [comment]
Same problem here. 
I checked the console, and it seems like it couldn't find the Python module

```
startup, version: 4180 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/kwlee/Library/Application Support/Sublime Text/Packages
state path: /Users/kwlee/Library/Application Support/Sublime Text/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/kwlee/Library/Application Support/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.471546
OpenGL Context Information:
  GL API Version: 4.1 ATI-6.1.13
  GLSL Version: 4.10
  Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon Pro Vega 64 OpenGL Engine
startup time: 0.591859
environment variables loaded using: /bin/zsh -l
first paint time: 0.65142
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.plugin
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin RainbowBrackets.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kwlee/Library/Application Support/Sublime Text/Installed Packages/RainbowBrackets.sublime-package/boot.py", line 18, in <module>
  File "/Users/kwlee/Library/Application Support/Sublime Text/Installed Packages/RainbowBrackets.sublime-package/plugin/__init__.py", line 5, in <module>
  File "/Users/kwlee/Library/Application Support/Sublime Text/Installed Packages/RainbowBrackets.sublime-package/plugin/manager.py", line 13, in <module>
  File "/Users/kwlee/Library/Application Support/Sublime Text/Installed Packages/RainbowBrackets.sublime-package/plugin/executor.py", line 7, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2024-11-13 10:23:11, next run at 2024-11-13 18:23:11 or after
ignored packages updated to: ["RainbowBrackets", "Vintage"]
unloading plugin RainbowBrackets.boot
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Removed package "RainbowBrackets"
Package Control: Error submitting usage information. HTTP error 500 downloading https://packagecontrol.io/submit?package=RainbowBrackets&operation=remove&version=4.3.1&package_control_version=4.0.8&sublime_platform=osx&sublime_version=4180.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by absop** [comment]
I released a new version with adding dependency configuration. Can you install version 4.3.2 to see if the problem has been fixed?
@carlomontec @yeoooo

**Comment by yeoooo** [comment]
After i installed 4.3.2, problem has been fixed 
thanks for your help :) 

![image](https://github.com/user-attachments/assets/3222e4e2-3044-4022-94ee-ff0e0e9a36c1)

**Comment by absop** [comment]
OK, thanks for your reply!

**Comment by carlomontec** [comment]
I can also confirm the last update solved the issue. Thanks a lot!

**Comment by sricks** [comment]
Not sure when this changed but I also had problems recently. After upgrading to latest version I got errors like: 
`AttributeError: 'RainbowBracketsExecutor' object has no attribute 'view'`

and a bunch of other things like key error for `err_key` in `executor.py`

Turns out my config file is no longer supported so I had to update my config file. This config will colorize on all files automatically. `rainbow_colors` key got split to `color.cycle` and `color.error`

Btw are you open to PRs about docs? Because I have found this package very difficult to use but it's a great package and easy to configure except there's no documentation.

I think at least stating when config keys change, maybe letting them be backwards compatible is nice too as it's annoying I have to update this.

```
/*
	RainbowBrackets user settings in here override the default
*/
{
	// Create a working default_config with coloring:true so that all files have rainbow brackets on open.
	// Otherwise, you have to use the command pallete to "Make Rainbow" in every single file.
	"default_config": {
		"bracket_pairs": {
			"(": ")",
			"[": "]",
			"{": "}",
		},

		"coloring": true,

		"enabled": true,

		"ignored_scopes": ["comment", "string", "constant"],

		"color.error": "#FF0000",

		"color.cycle": [
			"#FF0000", // level0
			"#FF6A00", // level1
			"#FFD800", // level2
			"#00FF00", // level3
			"#0094FF", // level4
			"#0041FF", // level5
			"#7D00E5" // level6
		],

		// rainbow_colors key got replaced by color.error, color.cycle sometime in 2024.
		"rainbow_colors": [
			"#FF0000", // level0
			"#FF6A00", // level1
			"#FFD800", // level2
			"#00FF00", // level3
			"#0094FF", // level4
			"#0041FF", // level5
			"#7D00E5" // level6
		],

		"mismatch_color": "#FF0000",
	},
}
```

**Comment by absop** [comment]
Thank you for your feedback @sricks , if you create this PR, I'll be happy to merge it.

My English is not good, so I didn't put much effort into the document. Thank you for your help in this regard.
